# Generated by Django 3.2.25 on 2024-11-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_rename_subscribed_at_newsletter_date_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_info', models.TextField(unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Information',
                'verbose_name_plural': 'Newsletter Information',
            },
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter Subscriber', 'verbose_name_plural': 'Newsletter Subscribers'},
        ),
    ]
