# Generated by Django 3.2.25 on 2024-10-30 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetier',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.IntegerField(default=1, help_text='Difficulty level from 1 (easiest) to 10 (most difficult)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
