# Generated by Django 3.2.25 on 2024-10-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20241030_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sku',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
