# Generated by Django 3.2.25 on 2024-11-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['difficulty']},
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
