# Generated by Django 3.2.25 on 2024-11-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('importance', models.PositiveIntegerField(default=1, help_text='Lower values indicate higher importance.')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['importance', 'created_on'],
            },
        ),
    ]
